POST /user HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name": "Edgar Martinez",
    "email":"edgar.m@gmail.com",
    "password":"edymartin1",
    "userName":"edyMartin",
    "gitToken":"token_****"
}