POST /git/issues HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "createRepo":{
        "repoUrl":"https://git.com.mx/qww",
        "descriptionIssue":"Error en campos invalidos "
    },
    "createUserRepos":{
        "level":"cinco"
    },
    "token":"ZWR5TWFydGluOjoyMDIzLTA0LTI5VDIyOjA0OjA5LjQ1NVo="
}